### ISSUE TITLE
Message failing to send at times.

### ISSUE THREAD

**Issue by ghost** [CodeCrafter47/FreeBungeeChat#2]
Sometimes when the players on my server try to send a message, this error pops up in BungeeCord, if it's something that I configured wrongly, would you mind telling me what it is? If you require a copy of my configuration file, please don't hesitate to ask.

14:01:39 [SEVERE] [FreeBungeeChat] Error while processing chat message
java.lang.RuntimeException: Unable to process chat message from Solace2o0 make sure you have installed FreeBungeeChat on Lobby
    at codecrafter47.freebungeechat.BukkitBridge.replaceVariables(BukkitBridge.java:129)
    at codecrafter47.freebungeechat.FreeBungeeChat.sendGlobalChatMessage(FreeBungeeChat.java:220)
    at codecrafter47.freebungeechat.FreeBungeeChat$2.run(FreeBungeeChat.java:194)
    at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)

**Comment by CodeCrafter47** [comment]
Possible reasons:
 1) You haven't installed FreeBungeeChat on your Lobby.
 2) The player whose chat message is affected is lagging or has just disconnected.
 3) Your Lobby server is lagging badly.

**Comment by ghost** [comment]
Hmm, the person in that particular error is myself, and when I was in the Lobby, there was no apparent signs of lag or anything. Tick rates were normal and my ping to the server was 95. Guess I'll have to do a little digging to find out what was causing it.
